# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy documents

on:
  push:
    branches: [ main ]
    paths: 
      - 'docs/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: |
        npm install
        npm run docs:build
      working-directory: docs
    - name: git setting
      run: |
        git config --global user.email "k_ota28@hotmail.com"
        git config --global user.name "runceel"
    - run: |
        git init
        git add --all
        git commit -m 'deploy'
        git push -f https://github.com/runceel/ReactiveProperty.git master:gh-pages
      working-directory: docs/docs/.vuepress/dist
