name: Unit testing

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.5.21302.13
    - name: Install ios workload
      run: dotnet workload install microsoft-ios-sdk-full
    - name: Install android workload
      run: dotnet workload install microsoft-android-sdk-full
    - name: Install dependencies
      run: dotnet restore ReactiveProperty.sln
    - name: Test
      run: dotnet test ReactiveProperty.sln --no-restore --verbosity normal
